### ISSUE TITLE
Fields not saving?

### ISSUE THREAD

**Issue by wasalwayshere** [imshuffling/contentful-custom-fields#1]
<img width="1128" alt="Screen Shot 2021-06-12 at 11 54 48 PM" src="https://user-images.githubusercontent.com/46236455/121798162-9b5f7c00-cbd9-11eb-95d0-77a11b43fac3.png">

Thanks for this boilerplate! I got it deployed using netlify (prod). But the fields aren't updating. I didn't change anything from the repo.

Any help would be appreciated!

**Comment by imshuffling** [comment]
Hey @wasalwayshere, do you have any errors in the console? it's been a while since I've looked at this.

**Comment by imshuffling** [comment]
I'm hosting the build folder on Heroku. Not sure if that makes a difference... Did a test and the fields are saving correctly. Are you adding this App onto a JSON field?
